server:
  port: 8082
  error:
    whitelabel:
      enabled: false
  tomcat:
    additional-tld-skip-patterns: "*.jar"



spring:
  servlet:
    encoding:
      charset:UTF-8
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode : HTML
    encoding: UTF-8
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ENC(Qzl2hieUGWyndT1EptjOpal1UsJB6k8tDLxpaIu8D/AZKjEsjVNMmR41hIBy45F0erOyt02MCQf5mhqQ1x5ZE0/BjLCuvylgaQ1+UHKSmAs=)
    username: ENC(XQcTrm7cbtoF3Wg/9oPzCw==)
    password: ENC(+JMqqj8qi35DczDTgIzw965Ji1lkuN1a)


  jasypt:
    encryptor:
      bean: jasyptStringEncryptor

  management:
    endpoints.enabled-by-default=false
    endpoint.info.enabled=true

  freemarker:
    checkTemplateLocation: false

mybatis:
  #type-aliases-package: com.ade.portfolio.*.mapper
  mapper-locations:
    - classpath*:/mappers/*/*.xml

logging:
  level:
    root: info