# 配置tomcat端口号
server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  servlet:
    encoding:
      charset:UTF-8
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode : HTML
    encoding: UTF-8
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: ENC(/WK1BZAlvEnLYPgTrcQlL393Euxa90+r0jPpKDyoi0S7ULuPUeEHEwfHPuMMYDdAVp986DSH19GdRpK4g3NCduyTI8AJOh3HkO1nsrNYv1k=)
    username: ENC(RMHjB+Q7TgJTXOZtMrORAA==)
    password: ENC(vwFsNez1nwfm7cWNw2kNY8mSqjxQaBX5)
  management:
    endpoints.enabled-by-default=false
    endpoint.info.enabled=true

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor

  freemarker:
    checkTemplateLocation: false

mybatis:
  #type-aliases-package: com.ade.portfolio.*.mapper
  mapper-locations:
    - classpath*:/mappers/*/*.xml

logging:
  level:
    root: info